# Generated by Django 2.1 on 2020-06-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(default=1, verbose_name='评论类型，默认为文章评论')),
                ('data_id', models.IntegerField(default=0, verbose_name='对应数据ID')),
                ('content', models.CharField(max_length=500, verbose_name='评论内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('del_flag', models.BooleanField(default=False, verbose_name='逻辑删除标记')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(default=0, verbose_name='父级评论ID')),
                ('content', models.CharField(max_length=500, verbose_name='评论内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('del_flag', models.BooleanField(default=False, verbose_name='逻辑删除标记')),
            ],
        ),
    ]
